# Generated by Django 5.0.6 on 2024-06-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_customuser_date_joined_remove_customuser_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
