# Generated by Django 4.2.6 on 2024-07-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_tasklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
