# Generated by Django 4.2.6 on 2024-07-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('number_plate', models.CharField(max_length=20, unique=True)),
                ('current_city', models.CharField(max_length=100)),
                ('rent_per_hr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_history', models.JSONField(default=list)),
            ],
        ),
    ]
